
"""init

Revision ID: 1a4df9631f8e
Revises: 
Create Date: 2025-12-30 09:28:56.873613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1a4df9631f8e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('capacity_kg', sa.Integer(), nullable=False),
    sa.Column('fuel_l_per_100km', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('drivers',
    sa.Column('tab_number', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('tab_number')
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('origin', sa.String(length=120), nullable=False),
    sa.Column('destination', sa.String(length=120), nullable=False),
    sa.Column('distance_km', sa.Integer(), nullable=False),
    sa.Column('car_number', sa.String(length=32), nullable=False),
    sa.Column('driver_tab_number', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['car_number'], ['cars.number'], ),
    sa.ForeignKeyConstraint(['driver_tab_number'], ['drivers.tab_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    op.drop_table('drivers')
    op.drop_table('cars')
    # ### end Alembic commands ###